### ISSUE TITLE
Comments starting with `/` not rendered properly

### ISSUE THREAD

**Issue by sohang3112** [fttx/language-forth#2]
Comments of the form `/ This line is a comment` are not rendered as comments. However, `( comments in brackets )` are rendered correctly. 

### Environment
- **VS Code:** Version 1.69.1 (latest)
- **OS:** Windows 11

**Comment by fttx** [comment]
Maybe @giovannimatina knows how to fix it

**Comment by sohang3112** [comment]
Sorry, I missed that comments in Forth actually begin with `\` (not `/`, as I was doing).
