### ISSUE TITLE
File type association

### ISSUE THREAD

**Issue by CCurl** [fttx/language-forth#4]
How would I associate files with other extensions with this?  My Forth files are *.c4, not *.f

Thanks

**Comment by fttx** [comment]
Change this: https://github.com/fttx/language-forth/blob/7e8d469620ca73747fa1323cbbb2440c52dc41a9/package.json#L21

Or alternatively, you should be able to specify it in your VS code settings by adding a item here:

![image](https://github.com/fttx/language-forth/assets/5663423/949a9f1b-e749-4786-9afc-d3d5bebe5342)

**Comment by CCurl** [comment]
For the 2nd option, what would you put for the value?
